version: '3'

services:
#  db_postgres:
#    networks:
#      - kamikaze
#    restart: on-failure
#    image: postgres:12.1-alpine
#    container_name: 'postgres_kamikaze'
#    environment:
#      - POSTGRES_DB=kamikaze
#      - POSTGRES_USER=postgres
#      # - POSTGRES_PASSWORD:docker
#    volumes:
#      - './database/postgres:/var/lib/postgresql/data'
#    ports:
#      - 5432:5432
  db_mongo:
    container_name: mongo_mudeime
    image: mongo:3.4.21-xenial
    ports:
      - 27017:27017
    networks:
      - banzinga
    restart: on-failure
    volumes:
      - ./database/mongodb:/var/lib/mongodb/data

  api_java:
    build: .
    networks:
      - banzinga
    links:
      - db_mongo
    depends_on:
      - db_mongo
    container_name: 'java_kamikaze'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_postgres:5432/kamikaze
    volumes:
      - .:/usr/app
    ports:
      - 8080:8080
    command: 'sh /usr/app/start.sh'
    env_file: .heroku


networks:
  banzinga:
